# Generated by Django 5.2.5 on 2025-08-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodysection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={},
        ),
        migrations.AlterModelTable(
            name='bodysection',
            table='body_section',
        ),
        migrations.AlterModelTable(
            name='cv',
            table='cv',
        ),
        migrations.AlterModelTable(
            name='header',
            table='header',
        ),
    ]
