# Generated by Django 5.2.5 on 2025-08-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_bodysection_options_alter_cv_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodysection',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.AlterField(
            model_name='bodysection',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_sections', to='cv.cv'),
        ),
    ]
