# Generated by Django 5.2.5 on 2025-08-23 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Shows whether the object is still relevant', verbose_name='IsActive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('linkedin_url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Shows whether the object is still relevant', verbose_name='IsActive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, default='', max_length=48, verbose_name='File name')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_files', to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(blank=True, help_text='Header of cv page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.header', verbose_name='Header')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Shows whether the object is still relevant', verbose_name='IsActive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
