services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  cv-builder:
    build: .
    container_name: cv-builder-container
    depends_on:
      - db
    volumes:
      - ./backend/static:/app/staticfiles
    env_file:
      - .env

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/static:ro
    depends_on:
      - cv-builder

volumes:
  postgres_data: {}
