FROM python:3.13.3-slim AS builder
 
RUN apt-get update && apt-get install -y curl build-essential libpq-dev

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONBUFFERED=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    PATH="/root/.local/bin:$PATH"

COPY backend/poetry.lock backend/pyproject.toml ./
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    poetry install --no-root --no-interaction --no-ansi

COPY backend/ ./backend/
COPY frontend/ ./frontend/
COPY .entrypoint.prod.sh /app/.entrypoint.prod.sh
RUN chmod +x /app/.entrypoint.prod.sh

EXPOSE 8000

CMD ["/app/.entrypoint.prod.sh"]