# Generated by Django 5.2.5 on 2025-08-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_rename_audit_requestlog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestlog',
            table='request_logs',
        ),
    ]
