# Generated by Django 5.2.5 on 2025-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_method', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=128)),
                ('duration', models.TimeField()),
            ],
        ),
    ]
