# Generated by Django 5.2.5 on 2025-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
