# Generated by Django 5.2.5 on 2025-08-25 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_audit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audit',
            new_name='RequestLog',
        ),
    ]
