# Generated by Django 5.2.5 on 2025-08-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_requestlog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='duration',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
